import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  turbopack: {
    resolveAlias: {
      '@': './src',
      '@public': './public',
    },
  },
  images: {
    qualities: [25, 50, 75, 100],
  },
  reactCompiler: true,
  async redirects() {
    return [
      // HIGH-TRAFFIC BLOG REDIRECTS
      { source: '/how-to-find-out-what-search-terms-people-use', destination: '/blog/how-to-find-out-what-search-terms-people-use', permanent: true },
      { source: '/how-to-find-out-what-search-terms-people-use/', destination: '/blog/how-to-find-out-what-search-terms-people-use', permanent: true },
      { source: '/which-colours-should-i-use-for-my-website-and-why', destination: '/blog/which-colours-should-i-use-for-my-website-and-why', permanent: true },
      { source: '/which-colours-should-i-use-for-my-website-and-why/', destination: '/blog/which-colours-should-i-use-for-my-website-and-why', permanent: true },
      { source: '/what-is-the-price-of-redesigning-a-website-in-2023', destination: '/blog/what-is-the-price-of-redesigning-a-website', permanent: true },
      { source: '/what-is-the-price-of-redesigning-a-website-in-2023/', destination: '/blog/what-is-the-price-of-redesigning-a-website', permanent: true },
      { source: '/types-of-websites', destination: '/blog/types-of-websites', permanent: true },
      { source: '/types-of-websites/', destination: '/blog/types-of-websites', permanent: true },
      { source: '/will-ai-take-over-web-development-and-web-design', destination: '/blog/will-ai-take-over-web-development', permanent: true },
      { source: '/will-ai-take-over-web-development-and-web-design/', destination: '/blog/will-ai-take-over-web-development', permanent: true },
      { source: '/how-much-does-a-website-cost-per-month', destination: '/blog/how-much-does-a-website-cost-per-month', permanent: true },
      { source: '/how-much-does-a-website-cost-per-month/', destination: '/blog/how-much-does-a-website-cost-per-month', permanent: true },
      { source: '/tips-to-protect-your-website-from-getting-hacked', destination: '/blog/tips-protect-website-from-hackers', permanent: true },
      { source: '/tips-to-protect-your-website-from-getting-hacked/', destination: '/blog/tips-protect-website-from-hackers', permanent: true },
      { source: '/why-is-responsive-design-good-for-small-business-websites', destination: '/blog/why-responsive-design-matters-for-small-business', permanent: true },
      { source: '/why-is-responsive-design-good-for-small-business-websites/', destination: '/blog/why-responsive-design-matters-for-small-business', permanent: true },
      { source: '/why-website-design-and-development-is-important-in-2023', destination: '/blog/why-website-design-and-development-is-important', permanent: true },
      { source: '/why-website-design-and-development-is-important-in-2023/', destination: '/blog/why-website-design-and-development-is-important', permanent: true },
      { source: '/why-businesses-sholuld-invest-in-crm-software-in-2023', destination: '/blog/why-businesses-should-invest-in-crm-software', permanent: true },
      { source: '/why-businesses-sholuld-invest-in-crm-software-in-2023/', destination: '/blog/why-businesses-should-invest-in-crm-software', permanent: true },
      { source: '/what-is-google-looking-for-on-your-website', destination: '/blog/what-is-google-looking-for-on-your-website', permanent: true },
      { source: '/what-is-google-looking-for-on-your-website/', destination: '/blog/what-is-google-looking-for-on-your-website', permanent: true },
      { source: '/using-schema-markup-to-increase-website-seo', destination: '/blog/seo-structured-data-schema-markup-guide', permanent: true },
      { source: '/using-schema-markup-to-increase-website-seo/', destination: '/blog/seo-structured-data-schema-markup-guide', permanent: true },
      { source: '/the-price-of-success-understanding-uk-website-development-costs', destination: '/blog/uk-website-development-costs', permanent: true },
      { source: '/the-price-of-success-understanding-uk-website-development-costs/', destination: '/blog/uk-website-development-costs', permanent: true },
      // OTHER BLOG REDIRECTS
      { source: '/a-guide-to-bristols-incredible-street-food', destination: '/blog', permanent: true },
      { source: '/shop-local-a-spotlight-on-bristols-independent-retailers', destination: '/blog', permanent: true },
      { source: '/a-guide-to-the-best-brunch-in-bristol', destination: '/blog', permanent: true },
      { source: '/google-beacon-business-benefits', destination: '/blog', permanent: true },
      { source: '/difference-between-mobile-site-and-responsive-design', destination: '/blog', permanent: true },
      { source: '/the-ultimate-guide-to-creating-high-converting-landing-pages-for-your-business', destination: '/blog', permanent: true },
      { source: '/google-search-generative-experience-web-optimization-tips-to-help-boost-your-online-prescence', destination: '/blog', permanent: true },
      { source: '/google-search-generative-experience-tips-2024', destination: '/blog', permanent: true },
      { source: '/a-detailed-article-explaining-the-web-design-and-development-process', destination: '/blog', permanent: true },
      { source: '/open-source-vs-proprietary-cms-which-content-management-system-to-choose', destination: '/blog', permanent: true },
      { source: '/adding-ssl-certificate-to-your-website-can-benefit-your-business', destination: '/blog', permanent: true },
      { source: '/website-design-ideas', destination: '/blog', permanent: true },
      { source: '/how-much-does-it-cost-to-design-a-website', destination: '/blog', permanent: true },
      { source: '/how-do-i-add-keywords-to-my-website', destination: '/blog', permanent: true },
      { source: '/how-to-choose-a-good-web-designer', destination: '/blog', permanent: true },
      { source: '/new-top-level-domain-names-and-their-seo-implications', destination: '/blog', permanent: true },
      { source: '/how-do-i-create-a-wordpress-website', destination: '/blog', permanent: true },
      { source: '/how-to-plan-an-seo-backlink-audit', destination: '/blog', permanent: true },
      { source: '/the-critical-benefits-of-achieving-cyber-essentials-certification', destination: '/blog', permanent: true },
      { source: '/the-benefits-of-parallax-scrolling-web-design', destination: '/blog', permanent: true },
      { source: '/how-can-i-promote-my-business-for-free', destination: '/blog', permanent: true },
      { source: '/implementing-the-best-seo-strategy-for-2017', destination: '/blog', permanent: true },
      { source: '/seo-best-strategy-2018', destination: '/blog', permanent: true },
      { source: '/reasons-to-have-a-mobile-website-design', destination: '/blog', permanent: true },
      { source: '/what-are-keywords-in-seo', destination: '/blog', permanent: true },
      // CONTACT
      { source: '/contact', destination: '/contact-us', permanent: true },
      { source: '/contact/', destination: '/contact-us', permanent: true },
      // PORTFOLIO
      { source: '/portfolio', destination: '/case-study', permanent: true },
      { source: '/portfolio/', destination: '/case-study', permanent: true },
      { source: '/portfolio-item/:path*', destination: '/case-study', permanent: true },
      // TERMS
      { source: '/terms-and-conditions', destination: '/terms-conditions', permanent: true },
      { source: '/terms-and-conditions/', destination: '/terms-conditions', permanent: true },
      // CAREERS
      { source: '/careers', destination: '/about', permanent: true },
      { source: '/careers/', destination: '/about', permanent: true },
      { source: '/careers/:path*', destination: '/about', permanent: true },
      // CATEGORIES AND TAGS
      { source: '/category/:path*', destination: '/blog', permanent: true },
      { source: '/tag/:path*', destination: '/blog', permanent: true },
      { source: '/author/:path*', destination: '/blog', permanent: true },
      // SERVICE REDIRECTS
      { source: '/web-design/web-design-services/consulting', destination: '/services/technical-strategy', permanent: true },
      { source: '/web-design/web-design-services/consulting/', destination: '/services/technical-strategy', permanent: true },
      { source: '/web-design-services/consulting', destination: '/services/technical-strategy', permanent: true },
      { source: '/web-design-services/consulting/', destination: '/services/technical-strategy', permanent: true },
      { source: '/web-development/sage-integration', destination: '/services/sage-50-api-integration', permanent: true },
      { source: '/web-development/sage-integration/', destination: '/services/sage-50-api-integration', permanent: true },
      { source: '/what-is-sage-ecommerce', destination: '/services/sage-50-api-integration', permanent: true },
      { source: '/what-is-sage-ecommerce/', destination: '/services/sage-50-api-integration', permanent: true },
      { source: '/web-design/website-redesign', destination: '/services/performance-optimisation', permanent: true },
      { source: '/web-design/website-redesign/', destination: '/services/performance-optimisation', permanent: true },
      { source: '/web-design/responsive-web-design', destination: '/services/bespoke-consultancy', permanent: true },
      { source: '/web-design/responsive-web-design/', destination: '/services/bespoke-consultancy', permanent: true },
      { source: '/web-development/database-development', destination: '/services/api-engineering', permanent: true },
      { source: '/web-development/database-development/', destination: '/services/api-engineering', permanent: true },
      { source: '/web-design-services/hosting', destination: '/services/secure-uk-hosting', permanent: true },
      { source: '/web-design-services/hosting/', destination: '/services/secure-uk-hosting', permanent: true },
      { source: '/web-design/web-design-services/hosting', destination: '/services/secure-uk-hosting', permanent: true },
      { source: '/web-design/web-design-services/hosting/', destination: '/services/secure-uk-hosting', permanent: true },
      { source: '/web-development/cms-development', destination: '/services/bespoke-cms', permanent: true },
      { source: '/web-development/cms-development/', destination: '/services/bespoke-cms', permanent: true },
      { source: '/web-design/web-design-services/search-engine-marketing', destination: '/services/performance-optimisation', permanent: true },
      { source: '/web-design/web-design-services/search-engine-marketing/', destination: '/services/performance-optimisation', permanent: true },
      { source: '/web-development/mobile-application-development', destination: '/services/next-js-react-development', permanent: true },
      { source: '/web-development/mobile-application-development/', destination: '/services/next-js-react-development', permanent: true },
      { source: '/web-design/mobile-web-design', destination: '/services/bespoke-consultancy', permanent: true },
      { source: '/web-design/mobile-web-design/', destination: '/services/bespoke-consultancy', permanent: true },
      { source: '/web-design/magento-web-development', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-design/magento-web-development/', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-design/ecommerce-website-design', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-design/ecommerce-website-design/', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-development/ecommerce-development', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-development/ecommerce-development/', destination: '/services/ecommerce-platforms', permanent: true },
      { source: '/web-design/brochure-web-design', destination: '/services/bespoke-consultancy', permanent: true },
      { source: '/web-design/brochure-web-design/', destination: '/services/bespoke-consultancy', permanent: true },
      // WILDCARD CATCH-ALLS (MUST BE LAST)
      { source: '/web-design/:path*', destination: '/services', permanent: true },
      { source: '/web-development/:path*', destination: '/services', permanent: true },
      { source: '/web-design-services/:path*', destination: '/services', permanent: true },
    ];
  },
};

export default nextConfig;
